### ISSUE TITLE
preference value not resolving but set in package.json

### ISSUE THREAD

**Issue by MattCampbell801** [binaryops-wiebo/ionic-msal-native#4]
Hi there,

I'm getting the following issue and my thinking is that for some reason the preference values are not resolving:
![Sign-in error](https://user-images.githubusercontent.com/53167567/109921266-44860480-7cc4-11eb-9541-73af64636577.png)

(in case the image doesn't show)
Application with identifier '$CLIENT_ID' was not found in the directory 'myDirectory'

1. I successfully get directed to Azure.
2. I then submit my credentials.
3. I then get the above error.

Android config.xml
  ```
<feature name="MsalPlugin">
    <param name="ios-package" value="MsalPlugin"/>
    <param name="onload" value="true"/>
    <preference name="tenantId" value="$TENANT_ID"/>
    <preference name="clientId" value="$CLIENT_ID"/>
  </feature>
```

iOS config.xml
```
  <feature name="MsalPlugin">
    <param name="ios-package" value="MsalPlugin"/>
    <param name="onload" value="true"/>
    <preference name="tenantId" value="$TENANT_ID"/>
    <preference name="clientId" value="$CLIENT_ID"/>
  </feature>
```

package.json
```
  "cordova": {
    "plugins": {
      "cordova-plugin-msal": {
        "TENANT_ID": "XxxxXXXXXXxx",
        "CLIENT_ID": "YYYyyyyYYYy",
        "KEY_HASH": "hash=" 
      }
    }
  }
```

Any help would be really appreciated thanks!

**Comment by wiebo-troost** [comment]
Hey, sorry to not get to this earlier. 
Did you resolve this problem? It appears to be a problem with the installation of the cordova plugin: https://github.com/wrobins/cordova-plugin-msal
